version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    container_name: openresearch-app
    volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - redis
      - weaviate

  postgres:
    image: postgres:13
    container_name: openresearch-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openresearch
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    container_name: openresearch-redis
    ports:
      - "6379:6379"

  weaviate:
    image: semitechnologies/weaviate:latest
    container_name: openresearch-weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: '20'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
  
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    ports:
      - "8888:8080"
    volumes:
      - ./searxng_settings.yml:/etc/searxng/settings.yml

volumes:
  pgdata:
  weaviate_data: